// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createPhpClient } from '@/lib/phpApiClient';

const SUPABASE_URL = "https://psjwlhngaltuxakupixr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzandsaG5nYWx0dXhha3VwaXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTMwODQsImV4cCI6MjA3MDY2OTA4NH0.pkfUdeQuhueeGPqliLx6pFgM2ozErAcFQz67yY9hXTw";

// Detect backend mode
const BACKEND_MODE = import.meta.env.VITE_BACKEND_MODE || 'supabase';
const PHP_API_URL = import.meta.env.VITE_PHP_API_URL || '/api';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let client: any;

if (BACKEND_MODE === 'php') {
  // Use PHP backend
  client = createPhpClient(PHP_API_URL);
  console.log('🔌 Using PHP backend at:', PHP_API_URL);
} else {
  // Use Supabase (default)
  client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = client;

// Export backend mode for conditional logic
export const isPhpBackend = BACKEND_MODE === 'php';
